title: HollerBen hoyt
description: "Ben Hoyt's personal website"
url: https://hustlerprince.github.io/Never-give-up/

# Defaults set by GitHub, only need for local serving
# https://help.github.com/articles/configuring-jekyll/
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true

# These are GitHub defaults too, but we don't need them
#gems:
#  - jekyll-coffeescript
#  - jekyll-paginate
